beauty
PECommunity/community pull request #16
Opened 2023-10-26 02:38 UTC by fleeto

翻译 TMI 3，#14

2023-10-26 08:59 UTC, node requested changes

2023-10-26 08:59 UTC, node commented on articles/TMI 2.md
> +持续性性是创造性思维的基础。可靠的环境、稳定的基础让人更倾向于突破界限，在舒适区之外进行创新。我们为客户创建的每个应用程序和环境都是他们下一代技术和业务战略的第一步，所以要讨论应用程序现代化，就必须要讨论耐久性。整个企业的目标和梦想都寄托在我们正在构建的技术架构上，因此需要确保基础具有足够的强度，能够承受未来将要面对的一切可能。
> 持续性性

多了一个 性 ？

2023-10-27 06:33 UTC, fleeto commented on articles/TMI 2.md
> +持续性性是创造性思维的基础。可靠的环境、稳定的基础让人更倾向于突破界限，在舒适区之外进行创新。我们为客户创建的每个应用程序和环境都是他们下一代技术和业务战略的第一步，所以要讨论应用程序现代化，就必须要讨论耐久性。整个企业的目标和梦想都寄托在我们正在构建的技术架构上，因此需要确保基础具有足够的强度，能够承受未来将要面对的一切可能。
Done

2023-10-27 06:44 UTC, node approved these changes

2023-10-27 06:45 UTC, node commented
LGTM.

2023-10-27 06:45 UTC, merged